### ISSUE TITLE
Add CSV / XLS output

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/metrics_service#132]
It would be nice to allow people to downloads the data behind the plots in a format that is easy to handle.
A CSV output for the metrics endpoint would not only allow us to put a button in the UI that says "download CSV" but it would also provide a friendly way for API users to get their data straight into a spreadsheet.

One webby way to do this would be via content negotiations, looking for an "Acccept: text/csv" HTTP header to see what the user is requesting as output format.

**Comment by ehenneken** [comment]
Since the UI has all the data, an alternative is to use JavaScript libraries to implement this. Using the micro service does not seem efficient, because it probably needs a second call, potentially lengthy.
