### ISSUE TITLE
Citation Histogram for single bibcode - year misalignment

### ISSUE THREAD

**Issue by ehenneken** [adsabs/metrics_service#141]
For a single bibcode, the output for the citation histogram can be as follows
```
{'skipped bibcodes': [], 'histograms': {'citations': {'refereed to refereed': {'2015': 0, '2016': 0, '2017': 0, '2018': 0, '2019': 0, '2020': 0, '2021': 0, '2022': 0}, 'refereed to nonrefereed': {'2015': 0, '2016': 3, '2017': 14, '2018': 61, '2019': 89, '2020': 127, '2021': 154, '2022': 140, '2023': 2}, 'nonrefereed to refereed': {'2015': 0, '2016': 0, '2017': 0, '2018': 0, '2019': 0, '2020': 0, '2021': 0, '2022': 0}, 'nonrefereed to nonrefereed': {'2015': 1, '2016': 74, '2017': 378, '2018': 397, '2019': 200, '2020': 257, '2021': 202, '2022': 127}, 'refereed to refereed normalized': {'2015': 0, '2016': 0, '2017': 0, '2018': 0, '2019': 0, '2020': 0, '2021': 0, '2022': 0}, 'refereed to nonrefereed normalized': {'2015': 0, '2016': 0.07500000000000001, '2017': 0.35000000000000003, '2018': 1.5249999999999986, '2019': 2.224999999999996, '2020': 3.1749999999999927, '2021': 3.8499999999999903, '2022': 3.4999999999999916, '2023': 0.05}, 'nonrefereed to refereed normalized': {'2015': 0, '2016': 0, '2017': 0, '2018': 0, '2019': 0, '2020': 0, '2021': 0, '2022': 0}, 'nonrefereed to nonrefereed normalized': {'2015': 0.025, '2016': 1.8499999999999974, '2017': 9.450000000000067, '2018': 9.925000000000074, '2019': 5.0000000000000036, '2020': 6.425000000000024, '2021': 5.050000000000004, '2022': 3.1749999999999927}}}}
```
Note that the `refereed to nonrefereed` attribute has an entry `2023` (and its normalized version), while the others  do not. In case of multiple bibcodes, the dictionaries get merged and years get aligned. This does not happen for a single bibcode. It's probably better to set `min_year` and `max_year` in a different way and maybe change the logic of populating the dictionaries (https://github.com/adsabs/metrics_service/blob/master/metrics_service/metrics.py#L483)

**Comment by aaccomazzi** [comment]
Note that this problem can happen when the request is for multiple bibcodes as well.  For example, as of today, this metrics display currently fails: https://ui.adsabs.harvard.edu/search/q=2017zndo...1069648C%20or%202022zndo...7226168H&sort=date%20desc%2C%20bibcode%20desc/metrics
probably because  `2017zndo...1069648C` has one refereed 2023 citation while `2022zndo...7226168H` has none.

**Comment by ehenneken** [comment]
The problem lies in
```
    try:
        max_year = max(max_year, max(rr_hist.keys()))
        max_year = max(max_year, max(rn_hist.keys()))
        max_year = max(max_year, max(nr_hist.keys()))
        max_year = max(max_year, max(nn_hist.keys()))
    except:
        pass
```
If any of these lists is empty, the `max` will throw an error. If the current year is `2022`, there is a `2023` citation somewhere, but any of the other histograms is empty, the `try` will fail and `max_year` will keep the value of the current year.

**Comment by aaccomazzi** [comment]
How about:
```
        max_year = max(max_year, max(rr_hist.keys() or [0]))
        max_year = max(max_year, max(rn_hist.keys() or [0]))
        max_year = max(max_year, max(nr_hist.keys() or [0]))
        max_year = max(max_year, max(nn_hist.keys() or [0]))
```
