### ISSUE TITLE
Add "recent views" to table of Usage (reads)

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/metrics_service#37]
We should add the 90-day window count (read_count in solr document) to the numbers displayed in the usage table.  This allows users to better understand how papers may be ranked when one chooses the "popularity" (soon to be called "recent views") ranking

**Comment by ehenneken** [comment]
The "recent views" are now available in the metrics output as "recent ADS reads" (i.e. "reads through the ADS for the current year") and "recent ADS downloads"

**Comment by aaccomazzi** [comment]
I may be confused about this, but I thought we decided that "recent views" is what we are going to call the 90-day read_count which includes arXiv, so I hope those are not the ones that you want to call "recent ADS reads"

**Comment by ehenneken** [comment]
The "recent views" (which includes the arXiv usage) will be what will get displayed on the query results page. The metrics overview will only contain numbers based on ADS data, so the "recent reads" in this specific context are essentially based on the last number in the list with yearly reads for each article.
