### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by vsudilov** [adsabs/metrics_service#4]
@ehenneken , one of us should implement configurable python `logging` at some point. Low prio right now, but let's leave this issue open/unassigned as a reminder.

**Comment by ehenneken** [comment]
The following events should get emitted to the logger:

1. If Solr returns a status other than 200 when getting bibcodes from a query (error)
2.  No identifiers where found for the bibcodes submitted (error)
3. If there are skipped bibcodes, report these (should have been in database) (warning)
4. Report the error if the results in "views" came back with an error (error)
5. Report home much time it took to calculate the metrics (info)
